= Data Cleansing in OpenShift.

In this workshop, we'll be learning how to perform basic Data Science and Machine Learning using OpenShift. The OpenShift platform greatly simplifies deploying and using the tools that are typically used in most Data Science workflows today. In particular, we'll be using the http://opendatahub.io[Open Data Hub^] project to deploy most of the infrastructure we'll be using in the lab today.

== Introduction to Open Data Hub

Open Data Hub (ODH) is an open source project based on https://kubeflow.org/[Kubeflow^] that provides open source AI tools for running large and distributed AI workloads on OpenShift Container Platform. Currently, the Open Data Hub project provides open source tools for data storage, distributed AI and Machine Learning (ML) workflows, Jupyter Notebook development environment and monitoring. The Open Data Hub project roadmap offers a view on new tools and integration the project developers are planning to add.

Open Data Hub includes several open source components, which can be individially enabled. They include:

* Apache Airflow
* Apache Kafka
* Apache Spark
* Apache Superset
* Argo
* Grafana
* JupyterHub
* Prometheus
* Seldon

Open Data Hub itself is deployed on OpenShift via an https://www.openshift.com/learn/topics/operators[Operator^]. Operators on OpenShift are responsible for managing https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Custom Resources^]. Custom resources allow for OpenShift users to create higher level objects in Kubernetes than are available via the basic Kubernetes API. For example, the AMQ Streams Operator defines a custom resource called "Kafka", which allows us to create a Kafka cluster. Operators can define more than one Custom Resource - the AMQ Streams Operator also allows for the creation of a "KafkaTopic" on our "Kafka" cluster.

== Data Cleansing

The first step in developing a model for machine learning is often cleansing the data on which we're going to operate. In this section of the workshop, we'll learn how to perform basic data cleansing using a set of data available on the Internet. We'll download the data in CSV format and use the Python https://pandas.pydata.org/[Pandas^] library to clean and visualize the data inside of a Jupyter notebook.

https://jupyter.org/[Jupyter notebooks^] are widely used throughout the data science community to organize, run, and share code. Jupyter supports many programming languages, but the most common languages used in data science are Python and R. This workshops examples will all be in Python, as will the code we use to train and run our model.

In this first exercise, we'll be deploying a Jupyter Hub instance for our user on OpenShift and loading a notebook that performs some basic data cleansing and visualization exercizes on COVID-19 data from the https://covidtracking.com/[COVID Tracking project^].


== Buckets and Bucket Notifications creation

=== Connect to JupyterHub

Click on the jupyterhub icon and look for the "Routes" section. Click on the route listed there.

Just click on this link, a new tab will open. Click on the button *Sign in with OpenShift*, and use your OpenTLC credentials to connect.+
On the first connection, OpenShift will ask to authorize the application to access your username just click *Allow selected permissions*.

=== Launch Jupyter

On the *Spawner Options* page select the *s2i-minimal-notebook:3.6* image from the first dropdown (this should be the default image), and click *Spawn* at the bottom.

Your Jupyter environment will take 15-20 seconds to launch.

It will display a _File Explore like_ interface. Click on the *xraylab_notebooks.git* folder, then on the *georgia_covidtracking.ipynb* file, which will launch the notebook.

